ALTER TABLE module_files
  DROP COLUMN IF EXISTS file_data,
  DROP COLUMN IF EXISTS file_url,
  DROP COLUMN IF EXISTS file_size_kb,
  ADD COLUMN IF NOT EXISTS file_path VARCHAR(1024) NULL AFTER file_name,
  ADD COLUMN IF NOT EXISTS file_size BIGINT UNSIGNED NULL AFTER file_path,
  ADD COLUMN IF NOT EXISTS mime_type VARCHAR(255) NULL AFTER file_size;
